### ISSUE TITLE
onPress does not work on Android

### ISSUE THREAD

**Issue by ZakSingh** [KirillGudkov/react-native-in-app-message#13]
The `onPress` prop doesn't work on Android on RN 0.61.5.

From looking at the source code, it looks to be because the notification is using `position: absolute`. This breaks the `<TapGestureHandler>`, as I've verified the `onTapHandlerStateChange` function isn't called on Android.

For more info about this issue see:
https://github.com/facebook/react-native/issues/22397

**Comment by kirgudkov** [comment]
@ZakSingh It works fine, please check this out https://github.com/KirillGudkov/in-app-message-example
And this https://github.com/KirillGudkov/react-native-in-app-message/issues/10

**Comment by ZakSingh** [comment]
#10 has the fix - all I had to do was render the notification below the app navigation (as is described in that issue). Thanks for the help (and sorry I didn't look through the closed issues)!
