### ISSUE TITLE
Version 1.0.2 from npm does not have a podspec file & how to with code examples

### ISSUE THREAD

**Issue by loic-lopez** [KirillGudkov/react-native-in-app-message#2]
Hello,

Thanks for this package!

I have just installed the package from yarn:
```bash
yarn add react-native-in-app-message
```
<img width="1394" alt="Capture d’écran 2019-09-01 à 15 48 19" src="https://user-images.githubusercontent.com/17724398/64077336-f3acde80-cccf-11e9-9d71-8a2aad133efb.png">

Also how to create the same notification style as your example:
<img width="250" alt="" src="https://user-images.githubusercontent.com/17552441/50741960-c9288580-1215-11e9-8a4f-d2baa8778329.gif">

Thanks for reply

**Comment by kirgudkov** [comment]
@loic-lopez  Hi, fixed podspec in `1.0.31` and you can check this out https://github.com/KirillGudkov/in-app-message-example
there is simple example (just like in readme :) is this not enough?))
