### ISSUE TITLE
Not Compatible with react native >= 0.60 

### ISSUE THREAD

**Issue by Bill-Niz** [KirillGudkov/react-native-in-app-message#5]
Cannot compile on iOS with react native 0.61

**Comment by kirgudkov** [comment]
@Bill-Niz Hi, check this out https://github.com/KirillGudkov/in-app-message-example
react native is 0.61.5
it works fine

I guess problem is `.podspec` file does not exists in npm after publishing. **Fixed that)**
Make sure you update package to `1.0.31`, `yarn add react-native-gesture-handler` and `pod install` after that
