### ISSUE TITLE
ForceTouchGestureHandler is not available on this platform

### ISSUE THREAD

**Issue by stami** [KirillGudkov/react-native-in-app-message#7]
Hi,

Notification.ios.js uses `ForceTouchGestureHandler` without checking whether force touch is available, causing a warning on non-supporting iPhones (all 11 models).

See the fallback component here:
https://github.com/software-mansion/react-native-gesture-handler/blob/0ea3d95d486544f9f64afb278ac6d149cf9bda5f/Gestures.js#L33

I may be able to submit a pull request later, but just creating an issue for now.

**Comment by kirgudkov** [comment]
Fixed in v1.0.32
